# Generated by Django 5.2 on 2025-04-11 08:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Наименование столика')),
                ('seats', models.PositiveSmallIntegerField(verbose_name='Кол-во мест')),
                ('location', models.CharField(choices=[('1', 'зал у окна'), ('2', 'основной зал'), ('3', 'терраса')], max_length=20, verbose_name='Расположение')),
            ],
            options={
                'verbose_name': 'Столик',
                'verbose_name_plural': 'Столики',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50, verbose_name='Имя клиента')),
                ('reservation_time', models.DateTimeField(verbose_name='На какое время забронировано')),
                ('duration_minutes', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Значение не должно быть меньше 1')], verbose_name='Время пребывания, мин')),
                ('table_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='reserv.table', verbose_name='Номер столика')),
            ],
            options={
                'verbose_name': 'Бронь',
                'verbose_name_plural': 'Брони',
                'ordering': ('id',),
            },
        ),
    ]
